SELECT 
  CAR_ID,
  IF(
    CAR_ID IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE '2022-10-16' BETWEEN start_date AND end_date
    ),
    '대여중',
    '대여 가능'
  ) AS AVAILABILITY
FROM 
  (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS CARS
ORDER BY 
  CAR_ID DESC;